apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: openedx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openedx-storage
  resources:
    requests:
      storage: 50Gi
