apiVersion: v1
kind: Secret
metadata:
  name: couchdb-secrets
  namespace: openedx
type: Opaque
data:
  adminUsername: YWRtaW4= # "admin" in base64
  adminPassword: cGFzc3dvcmQ= # "password" in base64
  cookieAuthSecret: TW9uc3RlckNvb2tpZVNlY3JldA== # "MonsterCookieSecret" in base64
  sharedSecret: QW5vdGhlclNlY3JldEZvckNvdWNoREI= # "AnotherSecretForCouchDB" in base64
