apiVersion: v1
kind: Service
metadata:
  name: couchdb-service
  namespace: openedx
  labels:
    app: couchdb
spec:
  selector:
    app: couchdb
  ports:
    - port: 5984
      targetPort: 5984
      name: couchdb
  clusterIP: None # Headless service for StatefulSet
